/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as ContactPokkaRouteImport } from './routes/contact/pokka'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as ProcessIndexRouteImport } from './routes/process/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesGoogleAdsRouteImport } from './routes/services/google-ads'
import { Route as ServicesIndex_pokaRouteImport } from './routes/services/index_poka'
import { Route as ServicesMaintenanceRouteImport } from './routes/services/maintenance'
import { Route as ServicesMetaAdsRouteImport } from './routes/services/meta-ads'
import { Route as ServicesSeoRouteImport } from './routes/services/seo'
import { Route as ServicesWebsitesRouteImport } from './routes/services/websites'
import { Route as WorkIndexRouteImport } from './routes/work/index'
import { Route as WorkSlugRouteImport } from './routes/work/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactPokkaRoute = ContactPokkaRouteImport.update({
  id: '/contact/pokka',
  path: '/contact/pokka',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessIndexRoute = ProcessIndexRouteImport.update({
  id: '/process/',
  path: '/process/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGoogleAdsRoute = ServicesGoogleAdsRouteImport.update({
  id: '/services/google-ads',
  path: '/services/google-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndex_pokaRoute = ServicesIndex_pokaRouteImport.update({
  id: '/services/index_poka',
  path: '/services/index_poka',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMaintenanceRoute = ServicesMaintenanceRouteImport.update({
  id: '/services/maintenance',
  path: '/services/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMetaAdsRoute = ServicesMetaAdsRouteImport.update({
  id: '/services/meta-ads',
  path: '/services/meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/services/seo',
  path: '/services/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebsitesRoute = ServicesWebsitesRouteImport.update({
  id: '/services/websites',
  path: '/services/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/contact/pokka': typeof ContactPokkaRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/index_poka': typeof ServicesIndex_pokaRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/meta-ads': typeof ServicesMetaAdsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/work/$slug': typeof WorkSlugRoute
  '/about/': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/process/': typeof ProcessIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/contact/pokka': typeof ContactPokkaRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/index_poka': typeof ServicesIndex_pokaRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/meta-ads': typeof ServicesMetaAdsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/work/$slug': typeof WorkSlugRoute
  '/about': typeof AboutIndexRoute
  '/blog': typeof BlogIndexRoute
  '/contact': typeof ContactIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/process': typeof ProcessIndexRoute
  '/services': typeof ServicesIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/contact/pokka': typeof ContactPokkaRoute
  '/services/google-ads': typeof ServicesGoogleAdsRoute
  '/services/index_poka': typeof ServicesIndex_pokaRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/meta-ads': typeof ServicesMetaAdsRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/websites': typeof ServicesWebsitesRoute
  '/work/$slug': typeof WorkSlugRoute
  '/about/': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/process/': typeof ProcessIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/terms'
    | '/thank-you'
    | '/blog/$slug'
    | '/contact/pokka'
    | '/services/google-ads'
    | '/services/index_poka'
    | '/services/maintenance'
    | '/services/meta-ads'
    | '/services/seo'
    | '/services/websites'
    | '/work/$slug'
    | '/about/'
    | '/blog/'
    | '/contact/'
    | '/pricing/'
    | '/process/'
    | '/services/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms'
    | '/thank-you'
    | '/blog/$slug'
    | '/contact/pokka'
    | '/services/google-ads'
    | '/services/index_poka'
    | '/services/maintenance'
    | '/services/meta-ads'
    | '/services/seo'
    | '/services/websites'
    | '/work/$slug'
    | '/about'
    | '/blog'
    | '/contact'
    | '/pricing'
    | '/process'
    | '/services'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/terms'
    | '/thank-you'
    | '/blog/$slug'
    | '/contact/pokka'
    | '/services/google-ads'
    | '/services/index_poka'
    | '/services/maintenance'
    | '/services/meta-ads'
    | '/services/seo'
    | '/services/websites'
    | '/work/$slug'
    | '/about/'
    | '/blog/'
    | '/contact/'
    | '/pricing/'
    | '/process/'
    | '/services/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ContactPokkaRoute: typeof ContactPokkaRoute
  ServicesGoogleAdsRoute: typeof ServicesGoogleAdsRoute
  ServicesIndex_pokaRoute: typeof ServicesIndex_pokaRoute
  ServicesMaintenanceRoute: typeof ServicesMaintenanceRoute
  ServicesMetaAdsRoute: typeof ServicesMetaAdsRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesWebsitesRoute: typeof ServicesWebsitesRoute
  WorkSlugRoute: typeof WorkSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  PricingIndexRoute: typeof PricingIndexRoute
  ProcessIndexRoute: typeof ProcessIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/pokka': {
      id: '/contact/pokka'
      path: '/contact/pokka'
      fullPath: '/contact/pokka'
      preLoaderRoute: typeof ContactPokkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process/': {
      id: '/process/'
      path: '/process'
      fullPath: '/process/'
      preLoaderRoute: typeof ProcessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/google-ads': {
      id: '/services/google-ads'
      path: '/services/google-ads'
      fullPath: '/services/google-ads'
      preLoaderRoute: typeof ServicesGoogleAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/index_poka': {
      id: '/services/index_poka'
      path: '/services/index_poka'
      fullPath: '/services/index_poka'
      preLoaderRoute: typeof ServicesIndex_pokaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/maintenance': {
      id: '/services/maintenance'
      path: '/services/maintenance'
      fullPath: '/services/maintenance'
      preLoaderRoute: typeof ServicesMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/meta-ads': {
      id: '/services/meta-ads'
      path: '/services/meta-ads'
      fullPath: '/services/meta-ads'
      preLoaderRoute: typeof ServicesMetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/services/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/websites': {
      id: '/services/websites'
      path: '/services/websites'
      fullPath: '/services/websites'
      preLoaderRoute: typeof ServicesWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  BlogSlugRoute: BlogSlugRoute,
  ContactPokkaRoute: ContactPokkaRoute,
  ServicesGoogleAdsRoute: ServicesGoogleAdsRoute,
  ServicesIndex_pokaRoute: ServicesIndex_pokaRoute,
  ServicesMaintenanceRoute: ServicesMaintenanceRoute,
  ServicesMetaAdsRoute: ServicesMetaAdsRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesWebsitesRoute: ServicesWebsitesRoute,
  WorkSlugRoute: WorkSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  PricingIndexRoute: PricingIndexRoute,
  ProcessIndexRoute: ProcessIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
